baseURL: "http://example.org/"
languageCode: "en-us"
title: "SpectrumBlog"
taxonomies:
  category: categories
  tag: tags

## navigation
sectionPagesMenu: "main"
menu:
  main:
    - name: Home
      url: /
      weight: 1
    
    - identifier: about
      name: About
      url: /about
      weight: 2

    - identifier: posts
      name: Posts
      url: /posts
      weight: 3
    
    