baseURL: "http://example.org/"
languageCode: "en-us"
title: "SpectrumBlog"


## navigation
sectionPagesMenu: "main"
menu:
  main:
    - name: Home
      url: /
      weight: 1
    
    - identifier: about
      name: About
      url: /about
      weight: 2

    - identifier: posts
      name: Posts
      weight: 3
    
    
    - name: InfoSec
      url: /infosec/
      parent: posts
    
    - name: Programming
      url: /programming/
      parent: posts

    - name: Neurobiology
      url: /neurobiology/
      parent: posts

    