baseURL: "http://example.org/"
languageCode: "en-us"
title: "SpectrumBlog"

theme: "spectrum"

paginate: 4

menu:
  main:
    - name: posts
      url: "/posts"
      weight: 1
    
    
taxonomies:
  category: categories
  #tag: tags